#                                                                        #
# Routes configuration                                                   #
#                                                                        #
# This file contains the configuration for the MVC router.               #
# Just add your own modifications as necessary.                          #
#                                                                        #
# Please refer to the FLOW3 manual for possible configuration options.   #
#                                                                        #

Fallback:
  uriPattern: ''
  controllerObjectNamePattern: F3\TYPO3\Frontend\Controller\DefaultController

Frontend:
  uriPattern: '[page].[@format]'
  controllerObjectNamePattern: F3\TYPO3\Frontend\Controller\DefaultController
  defaults:
    @page: index
    @format: html

Backend:
  uriPattern: 'typo3'
  controllerObjectNamePattern: F3\TYPO3\Backend\Controller\DefaultController
  defaults:
    @package: TYPO3

BackendLogin:
  uriPattern: 'login'
  controllerObjectNamePattern: F3\TYPO3\Backend\Controller\LoginController
  defaults:
    @package: TYPO3

ServiceWithControllerOnly:
  uriPattern: 'typo3/service/v1/[@controller]'
  controllerObjectNamePattern: F3\TYPO3\Service\Controller\@controllerController
  viewObjectNamePattern: F3\@package\Service\View\@controller\@action@format
  defaults:
    @package: TYPO3
    @format: json


ServiceWithControllerAndFormat:
  uriPattern: 'typo3/service/v1/[@controller].[@format]'
  controllerObjectNamePattern: F3\TYPO3\Service\Controller\@controllerController
  viewObjectNamePattern: F3\TYPO3\Service\View\@controller\@action@format
  defaults:
    @package: TYPO3
    @format: json

ServiceWithControllerAndId:
  uriPattern: 'typo3/service/v1/[@controller]/[id]'
  controllerObjectNamePattern: F3\TYPO3\Service\Controller\@controllerController
  viewObjectNamePattern: F3\TYPO3\Service\View\@controller\@action@format
  defaults:
    @package: TYPO3
    @format: json

ServiceWithControllerAndIdAndFormat:
  uriPattern: 'typo3/service/v1/[@controller]/[id].[@format]'
  controllerObjectNamePattern: F3\TYPO3\Service\Controller\@controllerController
  viewObjectNamePattern: F3\TYPO3\Service\View\@controller\@action@format
  defaults:
    @package: TYPO3
    @format: json


#                                                                        #
# Other routes (for experimentation)                                     #
#                                                                        #

Setup:
  uriPattern: 'typo3/setup'
  controllerObjectNamePattern: F3\TYPO3\Backend\Controller\DefaultController
  defaults:
    @action: setup
