#                                                                        #
# Default subroutes configuration for the TYPO3 package                  #
#                                                                        #

# $Id$

##
# Backend

-
  name: 'Authentication'
  uriPattern: 'typo3/login(/{@action}.{@format})'
  defaults:
    '@package':    'TYPO3'
    '@controller': 'Backend\Login'
    '@action':     'index'
    '@format':     'html'
-
  name:  'Logout'
  uriPattern: 'typo3/logout'
  defaults:
    '@package':    'TYPO3'
    '@controller': 'Backend\Login'
    '@action':     'logout'
-
  name:          'Setup'
  uriPattern:    'typo3/setup(/{@action})'
  defaults:
    '@package':    'TYPO3'
    '@controller': 'Backend\Setup'
    '@action':     'index'

-
  name:          'Backend Overview'
  uriPattern: 'typo3'
  defaults:
    '@package':    'TYPO3'
    '@controller': 'Backend\Backend'
    '@action':     'index'

##
# Frontend

-
  name:          'Frontend with path pointing to a page with type and format'
  uriPattern:    '{page}.{type}.{@format}'
  defaults:
    '@package':    'TYPO3'
    '@controller': 'Frontend\Page'
    '@action':     'show'
    '@format':     'html'
  routeParts:
    page:
      handler:    F3\TYPO3\Routing\PageRoutePartHandler

-
  name:          'Frontend with path pointing to a page and format'
  uriPattern:    '{page}.{@format}'
  defaults:
    '@package':    'TYPO3'
    '@controller': 'Frontend\Page'
    '@action':     'show'
    '@format':     'html'
  routeParts:
    page:
      handler:    F3\TYPO3\Routing\PageRoutePartHandler

-
  name:          'Frontend with path pointing to a page'
  uriPattern:    '{page}'
  defaults:
    '@package':    'TYPO3'
    '@controller': 'Frontend\Page'
    '@action':     'show'
    '@format':     'html'
  routeParts:
    page:
      handler:    F3\TYPO3\Routing\PageRoutePartHandler

-
  name: 'Frontend with optional path pointing to a page'
  uriPattern: '({page})'
  defaults:
    '@package':     'TYPO3'
    '@controller':  'Frontend\Page'
    '@action':      'show'
    '@format':      'html'
  routeParts:
    page:
      handler:    F3\TYPO3\Routing\PageRoutePartHandler
