#                                                                        #
# Default subroutes configuration for the TYPO3 package                  #
#                                                                        #

# $Id$

##
# Backend

--
  name: 'Authenticate'
  uriPattern: 'typo3/login'
  defaults:
    @package:    'TYPO3'
    @subpackage: 'Backend'
    @controller: 'Login'
    @action:     'index'

-
  name:          'Experimentation setup'
  uriPattern:    'typo3/setup'
  defaults:
    @package:    'TYPO3'
    @subpackage: 'Backend'
    @controller: 'Setup'
    @action:     'setup'

-
  name:          'Backend route'
  uriPattern:    'typo3(/{section})'
  defaults:
    @package:    'TYPO3'
    @subpackage: 'Backend'
    @controller: 'Backend'
    @action:     'index'
    section:     'frontend'

##
# REST Services

-
  name:          'Service with controller and optional format' 
  uriPattern:    'typo3/service/v1/{@controller}(.{@format})'
  defaults:
    @package:    'TYPO3'
    @subpackage: 'Service'
    @format:     'json'

-
  name:          'Service with controller, id and optional format'
  uriPattern:    'typo3/service/v1/{@controller}/{id}(.{@format})'
  defaults:
    @package:    'TYPO3'
    @subpackage: 'Service'
    @format:     'json'

##
# Frontend

-
  name:          'Frontend with page and optional format'
  uriPattern:    '{page}.{@format}'
  defaults:
    @package:    'TYPO3'
    @subpackage: 'Frontend'
    @controller: 'Page'
    @action:     'show'
    @format:     'html'
  routeParts:
    page:
      handler:    F3\TYPO3\Routing\PageRoutePartHandler

-
  name: 'Frontend root URI'
  uriPattern: ''
  defaults:
    @package:    'TYPO3'
    @subpackage: 'Frontend'
    @controller: 'Page'
