#                                                                        #
# Default subroutes configuration for the TYPO3 package                  #
#                                                                        #

##
# Backend

-
  name: 'Authentication'
  uriPattern: 'typo3/login(/{@action}.{@format})'
  defaults:
    '@package':    'TYPO3'
    '@controller': 'Login'
    '@action':     'index'
    '@format':     'html'
-
  name:  'Logout'
  uriPattern: 'typo3/logout'
  defaults:
    '@package':    'TYPO3'
    '@controller': 'Login'
    '@action':     'logout'
    '@format':     'html'
-
  name:          'Setup'
  uriPattern:    'typo3/setup(/{@action})'
  defaults:
    '@package':    'TYPO3'
    '@controller': 'Backend\Setup'
    '@action':     'index'
    '@format':     'html'

-
  name:          'Backend Overview'
  uriPattern:    'typo3'
  defaults:
    '@package':    'TYPO3'
    '@controller': 'Backend\Backend'
    '@action':     'index'
    '@format':     'html'

##
# REST services

-
  name:          'REST Service: Node actions with format'

  # Example URL: http://myhost/typo3/service/rest/v1/node/live/sites/phoenixdemotypo3org/homepage.json

  uriPattern:    'typo3/service/rest/v1/node/{node}.{@format}'
  defaults:
    '@package':    'TYPO3'
    '@subpackage': 'Service\Rest\V1'
    '@controller': 'Node'
    'service':     'REST'
  routeParts:
    node:
      handler:    F3\TYPO3\Routing\NodeServiceRoutePartHandler

-
  name:          'REST Service: Node actions without format'

  # Example URL: http://myhost/typo3/service/rest/v1/node/live/sites/phoenixdemotypo3org/homepage

  uriPattern:    'typo3/service/rest/v1/node/{node}'
  defaults:
    '@package':    'TYPO3'
    '@subpackage': 'Service\Rest\V1'
    '@controller': 'Node'
    'service':     'REST'
  routeParts:
    node:
      handler:    F3\TYPO3\Routing\NodeServiceRoutePartHandler

##
# Frontend

-
  name:          'Frontend content with format and type'
  uriPattern:    '{node}.html/{type}'
  defaults:
    '@package':    'TYPO3'
    '@subpackage': 'Service\Rest\V1'
    '@controller': 'Node'
    '@format':     'html'
    '@action':     'show'
    'service':     'Frontend'
  routeParts:
    node:
      handler:    F3\TYPO3\Routing\NodeRoutePartHandler

-
  name:          'Frontend content with format'
  uriPattern:    '{node}.html'
  defaults:
    '@package':    'TYPO3'
    '@subpackage': 'Service\Rest\V1'
    '@controller': 'Node'
    '@format':     'html'
    '@action':     'show'
    'service':     'Frontend'
  routeParts:
    node:
      handler:    F3\TYPO3\Routing\NodeRoutePartHandler

-
  name:          'Frontend content without a specified format'
  uriPattern:    '({node})'
  defaults:
    '@package':    'TYPO3'
    '@subpackage': 'Service\Rest\V1'
    '@controller': 'Node'
    '@format':     'html'
    '@action':     'show'
    'service':     'Frontend'
  routeParts:
    node:
      handler:    F3\TYPO3\Routing\NodeRoutePartHandler

-
  name: 'Fallback rule – for when no site has been defined yet'
  uriPattern: ''
  defaults:
    '@package':     'TYPO3'
    '@controller':  'Backend\Setup'
    '@action':      'index'
    '@format':      'html'
