#                                                                        #
# Default subroutes configuration for the TYPO3 package                  #
#                                                                        #

# $Id$

##
# Backend

-
  name: 'Authentication'
  uriPattern: 'typo3/login(/{@action}.{@format})'
  defaults:
    '@package':    'TYPO3'
    '@controller': 'Backend\Login'
    '@action':     'index'
    '@format':     'html'
-
  name:  'Logout'
  uriPattern: 'typo3/logout'
  defaults:
    '@package':    'TYPO3'
    '@controller': 'Backend\Login'
    '@action':     'logout'
-
  name:          'Setup'
  uriPattern:    'typo3/setup(/{@action})'
  defaults:
    '@package':    'TYPO3'
    '@controller': 'Backend\Setup'
    '@action':     'index'

-
  name:          'Backend Overview'
  uriPattern: 'typo3'
  defaults:
    '@package':    'TYPO3'
    '@controller': 'Backend\Backend'
    '@action':     'index'

##
# Content Service

-
  name:          'Generic content with node path pointing to a content object, with format and type'
  uriPattern:    '{content}.{@format}/{type}'
  defaults:
    '@package':    'TYPO3'
    '@controller': 'Content'
    '@action':     'show'
    '@format':     'html'
  routeParts:
    content:
      handler:    F3\TYPO3\Routing\ContentRoutePartHandler

-
  name:          'Generic content with node path pointing to a content object, with format'
  uriPattern:    '{content}.{@format}'
  defaults:
    '@package':    'TYPO3'
    '@controller': 'Content'
    '@action':     'show'
    '@format':     'html'
  routeParts:
    content:
      handler:    F3\TYPO3\Routing\ContentRoutePartHandler

-
  name:          'Generic content with optional node path pointing to a content object, with default format HTML'
  uriPattern:    '({content})'
  defaults:
    '@package':    'TYPO3'
    '@controller': 'Content'
    '@action':     'show'
    '@format':     'html'
  routeParts:
    content:
      handler:    F3\TYPO3\Routing\ContentRoutePartHandler

-
  name: 'Fallback rule – for when no site has been defined yet'
  uriPattern: ''
  defaults:
    '@package':     'TYPO3'
    '@controller':  'Backend\Setup'
    '@action':      'noSite'
    '@format':      'html'
