#                                                                        #
# Settings                                                               #
#                                                                        #
# This file contains settings for various parts of the application.      #
# Just add your own modifications as necessary.                          #
#                                                                        #
# Please refer to the default settings file(s) or the manuals for        #
# possible configuration options.                                        #
#                                                                        #

FLOW3:
  security:
    authentication:
      providers:
        DefaultProvider:
          providerClass: PersistedUsernamePasswordProvider
          entryPoint:
            WebRedirect:
              uri: typo3/login
      authenticationStrategy: oneToken
  mvc:
    notFoundController: F3\TYPO3\Controller\ErrorController
