#                                                                        #
# Settings                                                               #
#                                                                        #
# This file contains settings for various parts of the application.      #
# Just add your own modifications as necessary.                          #
#                                                                        #
# Please refer to the default settings file(s) or the manuals for        #
# possible configuration options.                                        #
#                                                                        #

TYPO3:
  FLOW3:
    security:
      authentication:
        providers:
          DefaultProvider:
            providerClass: PersistedUsernamePasswordProvider
            entryPoint:
              WebRedirect:
                uri: typo3/login
        authenticationStrategy: oneToken
    mvc:
      notFoundController: TYPO3\TYPO3\Controller\ErrorController


  TYPO3CR:
    contentTypes:


      'TYPO3.TYPO3:Page':
        superTypes: ['TYPO3.TYPO3CR:Folder']
        label: 'Page'


      'TYPO3.TYPO3:Section':
        label: 'Section'


      'TYPO3.TYPO3:ContentObject':
        label: 'Abstract content object'
        properties:
          _hidden:
            type: boolean
            label: 'Hidden'
            # A the "category" groups the properties together in "propertyGroups"
            category: 'visibility'
            # The higher the priority, the more important the property is.
            priority: 1
          _hiddenBeforeDate:
            type: date
            label: 'Hidden before date'
            category: 'visibility'
            priority: 10
          _hiddenAfterDate:
            type: date
            label: 'Hidden after date'
            category: 'visibility'
            priority: 11

        propertyGroups:
          visibility:
            label: 'Visibility'
            priority: 1

      'TYPO3.TYPO3:TwoColumn':
        superTypes: ['TYPO3.TYPO3:ContentObject']
        label: 'Two column content'

        # TODO: think about name; as the structure is ONLY created on the beginning...
        structure:
          left:
            type: 'TYPO3.TYPO3:Section'
          right:
            type: 'TYPO3.TYPO3:Section'


        properties:
          layout:
            type: string
            label: 'Layout'
            # TODO: maybe rename to "group"?
            category: column
            # TODO: maybe rename "placeholder" to "defaultContent" or "default"??
            placeholder: '50-50'
            options:
              '50-50': '50% / 50%'
              '75-25': '75% / 25%'
              '25-75': '25% / 75%'

				# TODO: rename "propertyGroups" to "categories" or "groups"?
        propertyGroups:
          column:
            label: 'Columns'
            priority: 10




      'TYPO3.TYPO3:Text':
        superTypes: ['TYPO3.TYPO3:ContentObject']
        label: 'Text'

        properties:
          headline:
            label: string
            placeholder: 'Enter headline here'
          text:
            label: string
            placeholder: '<p>Enter text here</p>'

        inlineEditableProperties: ['headline', 'text']


      'TYPO3.TYPO3:TextWithImage':
        label: 'Text with Image'
        superTypes: ['TYPO3.TYPO3:Text']
        properties:
          image:
            type: TYPO3\TYPO3\Domain\Model\Media\ImageVariant
            label: 'Image'
            category: image
          position:
            type: enum
            label: 'Image position'
            category: 'image'
            options:
              values:
                left: 'Left'
                right: 'Right'
        propertyGroups:
          image:
            label: 'Image'
            priority: 5


      'TYPO3.TYPO3:Html':
        superTypes: ['TYPO3.TYPO3:ContentObject']
        label: 'HTML foo'
        properties:
          source:
            type: string
            label: 'HTML Content'
            placeholder: '<p>Enter HTML here</p>'
            category: html
            userInterface:
              editor:
                class: T3.Content.UI.Editor.HtmlEditor
              renderer:
                class: T3.Content.UI.Renderer.Html

        propertyGroups:
          html:
            label: 'HTML'
            priority: 10


      'TYPO3.TYPO3:Plugin':
        superTypes: ['TYPO3.TYPO3:ContentObject']
        label: 'Generic plugin'

        properties:
          package:
            type: string
            label: 'Package'
            category: pluginSettings
          subpackage:
            type: string
            label: 'Subpackage'
            category: pluginSettings
          controller:
            type: string
            label: 'Controller Name'
            category: pluginSettings
          action:
            type: string
            label: 'Action'
            category: pluginSettings

        propertyGroups:
          pluginSettings:
            label: 'Plugin Settings'



  TYPO3:
    userInterface:
      string:
        editor:
          class: T3.Content.UI.Editor.TextField
        renderer:
          class: T3.Content.UI.Renderer.Text
      boolean:
        editor:
          class: T3.Content.UI.Editor.Checkbox
        renderer:
          class: T3.Content.UI.Renderer.Boolean
      'TYPO3\TYPO3\Domain\Model\Media\ImageVariant':
        editor:
          class: T3.Content.UI.Editor.Image
#          options:
#
        renderer:
          class: T3.Content.UI.Renderer.Image
      date:
        editor:
          class: T3.Content.UI.Editor.DateField
        renderer:
          class: T3.Content.UI.Renderer.Date
      enum:
        editor:
          class: T3.Content.UI.Editor.Selectbox
        renderer:
          class: T3.Content.UI.Renderer.Text
