#                                                                        #
# Settings                                                               #
#                                                                        #
# This file contains settings for various parts of the application.      #
# Just add your own modifications as necessary.                          #
#                                                                        #
# Please refer to the default settings file(s) or the manuals for        #
# possible configuration options.                                        #
#                                                                        #

TYPO3:
  FLOW3:
    security:
      authentication:
        providers:
          Typo3BackendProvider:
            providerClass: PersistedUsernamePasswordProvider
            requestPatterns:
              controllerObjectName: TYPO3\TYPO3\Controller\Backend\.*
            entryPoint:
              WebRedirect:
                uri: typo3/login
        authenticationStrategy: oneToken
    mvc:
      notFoundController: TYPO3\TYPO3\Controller\ErrorController


  TYPO3CR:
    contentTypes:
      'TYPO3.TYPO3:AbstractNode':
        properties:
          _hidden:
            type: boolean
            label: 'Hide'
            # A the "category" groups the properties together in "propertyGroups"
            category: 'visibility'
            # The higher the priority, the more important the property is.
            priority: 1
          _hiddenBeforeDateTime:
            type: date
            label: 'Hide before date'
            category: 'visibility'
            priority: 11
          _hiddenAfterDateTime:
            type: date
            label: 'Hide after date'
            category: 'visibility'
            priority: 10
        propertyGroups:
          visibility:
            label: 'Visibility'
            priority: 1

      'TYPO3.TYPO3:TwoColumn':
        superTypes: ['TYPO3.TYPO3:ContentObject']
        label: 'Two column content'
        group: 'Structure'
        icon: 'Images/Icons/White/columns_icon-16.png'

        # TODO: think about name; as the structure is ONLY created on the beginning...
        structure:
          left:
            type: 'TYPO3.TYPO3:Section'
          right:
            type: 'TYPO3.TYPO3:Section'


        properties:
          layout:
            type: enum
            label: 'Layout'
            # TODO: maybe rename to "group"?
            category: column
            options:
              default: 'Select layout'
              items:
                -
                  value: '50-50'
                  label: '50% / 50%'
                -
                  value: '75-25'
                  label: '75% / 25%'
                -
                  value: '25-75'
                  label: '25% / 75%'
            reloadOnChange: true

        # TODO: rename "propertyGroups" to "categories" or "groups"?
        propertyGroups:
          column:
            label: 'Columns'
            priority: 10


      'TYPO3.TYPO3:Page':
        superTypes: ['TYPO3.TYPO3CR:Folder', 'TYPO3.TYPO3:AbstractNode']
        label: 'Page'
        search: 'Pages'
        icon: 'Images/Icons/White/doc_empty_icon-16.png'
        properties:
          title:
            type: string
            label: 'Page title'
            category: 'page'
            reloadOnChange: true
        propertyGroups:
          page:
            label: 'Page options'
            priority: 10


      'TYPO3.TYPO3:Section':
        label: 'Section'


      'TYPO3.TYPO3:ContentObject':
        superTypes: ['TYPO3.TYPO3:AbstractNode']
        label: 'Abstract content object'
        search: 'Content'


      'TYPO3.TYPO3:Text':
        superTypes: ['TYPO3.TYPO3:ContentObject']
        group: 'General'
        icon: 'Images/Icons/White/doc_lines_stright_icon-16.png'
        label: 'Text'

        properties:
          headline:
            label: string
            default: 'Enter headline here'
          text:
            label: string
            default: '<p>Enter text here</p>'

        inlineEditableProperties: ['headline', 'text']


      'TYPO3.TYPO3:TextWithImage':
        label: 'Text with Image'
        superTypes: ['TYPO3.TYPO3:Text']
        group: 'General'
        icon: 'Images/Icons/White/picture_icon-16.png'
        properties:
          image:
            type: TYPO3\Media\Domain\Model\ImageVariant
            label: 'Image'
            category: image
            reloadOnChange: true
          position:
            type: enum
            label: 'Image position'
            category: 'image'
            options:
              values:
                left:
                  label: 'Left'
                right:
                  label: 'Right'
            reloadOnChange: true
        propertyGroups:
          image:
            label: 'Image'
            priority: 5


      'TYPO3.TYPO3:Html':
        superTypes: ['TYPO3.TYPO3:ContentObject']
        group: 'General'
        icon: 'Images/Icons/White/brackets_icon-16.png'
        label: 'HTML'
        properties:
          source:
            type: string
            label: 'HTML Content'
            default: '<p>Enter HTML here</p>'
            category: html
            userInterface:
              class: T3.Content.UI.Editor.HtmlEditor

        propertyGroups:
          html:
            label: 'HTML'
            priority: 10


      'TYPO3.TYPO3:Plugin':
        superTypes: ['TYPO3.TYPO3:ContentObject']
        icon: 'Images/Icons/White/app_window_shell_icon-16.png'
        label: 'Abstract plugin'

        properties:
          package:
            type: string
            label: 'Package'
            category: pluginSettings
            reloadOnChange: true
          subpackage:
            type: string
            label: 'Subpackage'
            category: pluginSettings
            reloadOnChange: true
          controller:
            type: string
            label: 'Controller Name'
            category: pluginSettings
            reloadOnChange: true
          action:
            type: string
            label: 'Action'
            category: pluginSettings
            reloadOnChange: true

        propertyGroups:
          pluginSettings:
            label: 'Plugin Settings'

      'TYPO3.TYPO3:GenericPlugin':
        superTypes: ['TYPO3.TYPO3:Plugin']
        group: 'Plugins'
        label: 'Generic plugin'

        properties:
          package:
            category: pluginSettings
          subpackage:
            category: pluginSettings
          controller:
            category: pluginSettings
          action:
            category: pluginSettings


  TYPO3:
    contentTypeGroups: ['General', 'Structure', 'Plugins']

    userInterface:
      string:
        class: T3.Content.UI.Editor.TextField
      integer:
        class: T3.Content.UI.Editor.TextField
      boolean:
        class: T3.Content.UI.Editor.Checkbox
      'TYPO3\Media\Domain\Model\ImageVariant':
        class: T3.Content.UI.Editor.Image
      date:
        class: T3.Content.UI.Editor.DateField
      enum:
        class: T3.Content.UI.Editor.Selectbox
