#                                                                        #
# Settings                                                               #
#                                                                        #
# This file contains settings for various parts of the application.      #
# Just add your own modifications as necessary.                          #
#                                                                        #
# Please refer to the default settings file(s) or the manuals for        #
# possible configuration options.                                        #
#                                                                        #

TYPO3:
  FLOW3:
    security:
      authentication:
        providers:
          Typo3BackendProvider:
            provider: 'PersistedUsernamePasswordProvider'
            requestPatterns:
              controllerObjectName: "TYPO3\TYPO3\Controller\.*|TYPO3\TYPO3\Service\.*"
            entryPoint: 'WebRedirect'
            entryPointOptions:
              uri: typo3/login
        authenticationStrategy: oneToken
    mvc:
      notFoundController: TYPO3\TYPO3\Controller\ErrorController

  DocTools:
    bundles:
      Phoenix:
        documentationRootPath: %FLOW3_PATH_PACKAGES%Application/TYPO3.TYPO3/Documentation/
        configurationRootPath: %FLOW3_PATH_PACKAGES%Application/TYPO3.DocTools/Resources/Private/Themes/TYPO3/
        renderedDocumentationRootPath: %FLOW3_PATH_DATA%Temporary/Documentation/TYPO3.TYPO3/
        renderingOutputFormat: 'html'
        renderByDefault: false

  TYPO3CR:
    contentTypes:
      'TYPO3.TYPO3:AbstractNode':
        properties:
          _removed:
            type: boolean
          _hidden:
            type: boolean
            label: 'Hide'
            # The "group" groups the properties together in "(property)groups"
            group: 'visibility'
            # The higher the priority, the more important the property is.
            priority: 1
          _hiddenBeforeDateTime:
            type: date
            label: 'Hide before date'
            group: 'visibility'
            priority: 11
          _hiddenAfterDateTime:
            type: date
            label: 'Hide after date'
            group: 'visibility'
            priority: 10
        groups:
          visibility:
            label: 'Visibility'
            priority: 1

      'TYPO3.TYPO3:Section':
        superTypes: ['TYPO3.TYPO3:AbstractNode']
        label: 'Section'
        icon: 'Images/Icons/White/page_layout_icon-16.png'
        darkIcon: 'Images/Icons/Black/page_layout_icon-16.png'

      'TYPO3.TYPO3:Shortcut':
        superTypes: ['TYPO3.TYPO3CR:Folder', 'TYPO3.TYPO3:AbstractNode']
        label: 'Shortcut'

      'TYPO3.TYPO3:Page':
        superTypes: ['TYPO3.TYPO3CR:Folder', 'TYPO3.TYPO3:AbstractNode']
        label: 'Page'
        search: 'Pages'
        icon: 'Images/Icons/White/doc_empty_icon-16.png'
        darkIcon: 'Images/Icons/Black/doc_empty_icon-16.png'
        properties:
          title:
            type: string
            label: 'Page title'
            group: 'page'
            reloadOnChange: true
        groups:
          page:
            label: 'Page options'
            priority: 10

      'TYPO3.TYPO3:ContentObject':
        superTypes: ['TYPO3.TYPO3:AbstractNode']
        label: 'Abstract content object'
        search: 'Content'
        properties:
          title:
            type: 'string'
            label: 'Content Title'

      'TYPO3.TYPO3:Headline':
        superTypes: ['TYPO3.TYPO3:ContentObject']
        group: 'General'
        icon: 'Images/Icons/White/text_letter_t_icon-16.png'
        darkIcon: 'Images/Icons/Black/text_letter_t_icon-16.png'
        label: 'Headline'
        properties:
          title:
            default: '<h1>Enter headline here</h1>'
        inlineEditableProperties: ['title']

      'TYPO3.TYPO3:Text':
        superTypes: ['TYPO3.TYPO3:Headline']
        group: 'General'
        icon: 'Images/Icons/White/doc_lines_stright_icon-16.png'
        darkIcon: 'Images/Icons/Black/doc_lines_stright_icon-16.png'
        label: 'Text'
        properties:
          text:
            label: string
            default: '<p>Enter text here</p>'
        inlineEditableProperties: ['title', 'text']

      'TYPO3.TYPO3:Image':
        label: 'Image'
        superTypes: ['TYPO3.TYPO3:Headline']
        group: 'General'
        icon: 'Images/Icons/White/picture_icon-16.png'
        darkIcon: 'Images/Icons/Black/picture_icon-16.png'
        properties:
          image:
            type: TYPO3\Media\Domain\Model\ImageVariant
            label: 'Image'
            group: 'image'
            reloadOnChange: true
        groups:
          image:
            label: 'Image'
            priority: 5

      'TYPO3.TYPO3:TextWithImage':
        label: 'Text with Image'
        superTypes: ['TYPO3.TYPO3:Image', 'TYPO3.TYPO3:Text']
        group: 'General'
        icon: 'Images/Icons/White/image_text_icon-16.png'
        darkIcon: 'Images/Icons/Black/image_text_icon-16.png'
        properties:
          position:
            type: enum
            label: 'Image position'
            group: 'image'
            options:
              values:
                left:
                  label: 'Left'
                right:
                  label: 'Right'
            reloadOnChange: true

      'TYPO3.TYPO3:Html':
        superTypes: ['TYPO3.TYPO3:ContentObject']
        group: 'General'
        icon: 'Images/Icons/White/brackets_icon-16.png'
        darkIcon: 'Images/Icons/Black/brackets_icon-16.png'
        label: 'HTML'
        properties:
          source:
            type: string
            label: 'HTML Content'
            default: '<p>Enter HTML here</p>'
            group: 'html'
            userInterface:
              class: T3.Content.UI.Editor.HtmlEditor
        groups:
          html:
            label: 'HTML'
            priority: 10

      'TYPO3.TYPO3:Menu':
        superTypes: ['TYPO3.TYPO3:ContentObject']
        group: 'Structure'
        icon: 'Images/Icons/White/list_bullets_icon-16.png'
        darkIcon: 'Images/Icons/Black/list_bullets_icon-16.png'
        label: 'Menu'
        properties:
          startLevel:
            type: enum
            label: 'Starting Level'
            group: 'options'
            reloadOnChange: true
            default: '0'
            options:
              values:
                '-4':
                  label: 'Four Levels Above Current Page'
                '-3':
                  label: 'Three Levels Above Current Page'
                '-2':
                  label: 'Two Levels Above Current Page'
                '-1':
                  label: 'One Level Above Current Page'
                '0':
                  label: 'Same Level As Current Page'
                '1':
                  label: 'First Level Of Website'
                '2':
                  label: 'Second Level Of Website'
                '3':
                  label: 'Third Level Of Website'
                '4':
                  label: 'Forth Level Of Website'
                '5':
                  label: 'Fifth Level Of Website'
                '6':
                  label: 'Sixth Level Of Website'
          maximumLevels:
            type: enum
            label: 'Maximum Levels'
            group: 'options'
            reloadOnChange: true
            default: '1'
            options:
              values:
                '1':
                  label: '1'
                '2':
                  label: '2'
                '3':
                  label: '3'
                '4':
                  label: '4'
                '5':
                  label: '5'
                '6':
                  label: '6'
                '7':
                  label: '7'
                '8':
                  label: '8'
                '9':
                  label: '9'
                '10':
                  label: '10'
        groups:
         options:
           label: 'Options'
           priority: 30

      'TYPO3.TYPO3:Column':
        superTypes: ['TYPO3.TYPO3:ContentObject']
        icon: 'Images/Icons/White/columns_icon-16.png'
        darkIcon: 'Images/Icons/Black/columns_icon-16.png'
        properties:
          layout:
            type: enum
            label: 'Layout'
            group: 'column'
        groups:
          column:
            label: 'Columns'
            priority: 10

      'TYPO3.TYPO3:TwoColumn':
        superTypes: ['TYPO3.TYPO3:Column']
        group: 'Structure'
        label: 'Two column content'
        structure:
          column0:
            type: 'TYPO3.TYPO3:Section'
          column1:
            type: 'TYPO3.TYPO3:Section'
        properties:
          layout:
            default: '50-50'
            options:
              values:
                '50-50':
                  label: '50% / 50%'
                '75-25':
                  label: '75% / 25%'
                '25-75':
                  label: '25% / 75%'
                '66-33':
                  label: '66% / 33%'
                '33-66':
                  label: '33% / 66%'
            reloadOnChange: true

      'TYPO3.TYPO3:ThreeColumn':
        superTypes: ['TYPO3.TYPO3:Column']
        group: 'Structure'
        label: 'Three column content'
        structure:
          column0:
            type: 'TYPO3.TYPO3:Section'
          column1:
            type: 'TYPO3.TYPO3:Section'
          column2:
            type: 'TYPO3.TYPO3:Section'
        properties:
          layout:
            default: '33-33-33'
            options:
              values:
                '33-33-33':
                  label: '33% / 33% / 33%'
                '50-25-25':
                  label: '50% / 25% / 25%'
                '25-50-25':
                  label: '25% / 50% / 25%'
                '25-25-50':
                  label: '25% / 25% / 50%'
            reloadOnChange: true

      'TYPO3.TYPO3:FourColumn':
        superTypes: ['TYPO3.TYPO3:Column']
        group: 'Structure'
        label: 'Four column content'
        structure:
          column0:
            type: 'TYPO3.TYPO3:Section'
          column1:
            type: 'TYPO3.TYPO3:Section'
          column2:
            type: 'TYPO3.TYPO3:Section'
          column3:
            type: 'TYPO3.TYPO3:Section'
        properties:
          layout:
            default: '25-25-25-25'
            options:
              values:
                '25-25-25-25':
                  label: '25% / 25% / 25% / 25%'
            reloadOnChange: true

      'TYPO3.TYPO3:Plugin':
        superTypes: ['TYPO3.TYPO3:ContentObject']
        icon: 'Images/Icons/White/app_window_shell_icon-16.png'
        darkIcon: 'Images/Icons/Black/app_window_shell_icon-16.png'
        label: 'Abstract plugin'
        properties:
          package:
            type: string
            label: 'Package'
            group: 'pluginSettings'
            reloadOnChange: true
          subpackage:
            type: string
            label: 'Subpackage'
            group: 'pluginSettings'
            reloadOnChange: true
          controller:
            type: string
            label: 'Controller Name'
            group: 'pluginSettings'
            reloadOnChange: true
          action:
            type: string
            label: 'Action'
            group: 'pluginSettings'
            reloadOnChange: true
        groups:
          pluginSettings:
            label: 'Plugin Settings'

  TYPO3:
    contentTypeGroups: ['General', 'Structure', 'Plugins']

    userInterface:
      string:
        class: T3.Content.UI.Editor.TextField
      integer:
        class: T3.Content.UI.Editor.TextField
      boolean:
        class: T3.Content.UI.Editor.Checkbox
      'TYPO3\Media\Domain\Model\ImageVariant':
        class: T3.Content.UI.Editor.Image
      date:
        class: T3.Content.UI.Editor.DateField
      enum:
        class: T3.Content.UI.Editor.Selectbox

    moduleConfiguration:
      widgetTemplatePathAndFileName: 'resource://TYPO3.TYPO3/Private/Templates/Module/Widget.html'
    modules:
      management:
        label: 'Management'
        submodules:
          usersettings:
            label: 'User Settings'
            controller: '\TYPO3\TYPO3\Controller\Module\Management\UserSettingsController'
            description: "This module allows you to customize your backend user profile. Here you can change your active system language, name and email address. You may also configure other general features in the system."
            icon: 'resource://TYPO3.TYPO3/Public/Images/Icons/Orange/user_icon-24.png'
          workspaces:
            label: 'Workspaces'
            controller: '\TYPO3\TYPO3\Controller\Module\Management\WorkspacesController'
            description: "This module contains the overview of all elements within the current workspace and it enables to continue the review and publishing workflow for them."
            icon: 'resource://TYPO3.TYPO3/Public/Images/Icons/Orange/layers_1_icon-24.png'
      administration:
        label: 'Administration'
        submodules:
          users:
            label: 'User Management'
            controller: '\TYPO3\TYPO3\Controller\Module\Administration\UsersController'
            description: "The User Management module provides you with an overview of all backend users. You can group them by their properties so you're able to monitor their permissions, filemounts, member groups etc.. This module is an indispensable tool in order to make sure the users are correctly configured."
            icon: 'resource://TYPO3.TYPO3/Public/Images/Icons/Orange/users_icon-24.png'
            actions:
              new:
                label: 'Create user'
                title: 'Create a new user'
          packages:
            label: 'Package Management'
            controller: '\TYPO3\TYPO3\Controller\Module\Administration\PackagesController'
            description: "The Package Management module provides you with an overview of all packages. You can activate and deactivate individual packages, import new packages and delete existing packages. It also provides you with the ability to freeze and unfreeze packages in development context."
            icon: 'resource://TYPO3.TYPO3/Public/Images/Icons/Orange/box_icon-24.png'

  Setup:
    stepOrder: ['database', 'administrator', 'siteimport', 'final']
    steps:
      administrator:
        className: 'TYPO3\TYPO3\Setup\Step\AdministratorStep'
        requiredConditions:
          - className: 'TYPO3\Setup\Condition\DatabaseConnectionCondition'
      siteimport:
        className: 'TYPO3\TYPO3\Setup\Step\SiteImportStep'
        requiredConditions:
          - className: 'TYPO3\Setup\Condition\DatabaseConnectionCondition'
      final:
        className: 'TYPO3\TYPO3\Setup\Step\FinalStep'
